### ISSUE TITLE
Output format error using multiple threads

### ISSUE THREAD

**Issue by FlorianKleemiss** [peterspackman/occ#30]
Dear Peter,

I was using OCC for a small calculation, and I am delighted with the results when I am using a single core. I want to use the resulting wavefunction in another software that can only read the fchk format with spherical basis functions, hence I use the following command line call on a Windows machine:

`.\occ\bin\occ.exe scf alanine.xyz r2scan def2-tzvpp --spherical -d def2-universal-jkfit --basis-set-directory ./occ/bin -o fchk`

However, when I want to use multiple cores, if I understood the help correctly, the call would be:

`.\occ\bin\occ.exe --threads{26} scf alanine.xyz r2scan def2-tzvpp --spherical -d def2-universal-jkfit --basis-set-directory ./occ/bin -o fchk`

When using this, I am informed that: 

> occ.exe: A value that is not valid (fchk) was specified for the outputFormat parameter. Valid values are Text and Xml.

Am I misinterpreting the help, and is multithreading impossible for the scf? Or am I misplacing the keyword? I would appreciate any help!

Best wishes

**Comment by MilitaoLucas** [comment]
Did you try to do it using a toml file? 
```toml
threads = 26
verbosity = 2

[scf]
input = "cucomplex.xyz"
method = "r2scan"
basis = "def2-tzvpp"
spherical = true
df_basis = "def2-universal-jkfit"
basis-set-directory = "./occ/bin"
output = "fchk"
```
`.\occ\bin\occ.exe scf --config config.toml`
I think it could work.
