### ISSUE TITLE
toml issue on df_basis

### ISSUE THREAD

**Issue by MilitaoLucas** [peterspackman/occ#31]
Hello, I am having the following issue on toml when reading the following file:
```toml
threads = 30
verbosity = 2

[scf]
input = "cucomplex.xyz"
method = "r2scan"
basis = "def2-tzvp"
charge = 0
multiplicity = 2
output = "fchk"
spherical = true
df_basis = "def2-universal-jkfit"
```
This gives out:
`INI was not able to parse scf.df_basis`
```toml
threads = 30
verbosity = 2

[scf]
input = "cucomplex.xyz"
method = "r2scan"
basis = "def2-tzvp"
charge = 0
multiplicity = 2
output = "fchk"
spherical = true
density_fitting_basis = "def2-universal-jkfit"
```
this seems to work fine.
